<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WebSocketServer\Module'                        => __DIR__ . '/Module.php',
    'WebSocketServer\Controller\WebSocketServerController' => __DIR__ . '/src/WebSocketServer/Controller/WebSocketServerController.php',
    'WebSocketServerTest\Framework\TestCase'        => __DIR__ . '/tests/WebSocketServer/Framework/TestCase.php',
    'WebSocketServerTest\SampleTest'                => __DIR__ . '/tests/WebSocketServer/SampleTest.php',
);
